In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset = pd.read_csv('Book1.csv')
dataset

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s   CGPA   degree_t  \
0        1      M  67.00   Others  91.00   Others  Commerce  58.00   Sci&Tech   
1        2      M  79.33  Central  78.33   Others   Science  77.48   Sci&Tech   
2        3      M  65.00  Central  68.00  Central      Arts  64.00  Comm&Mgmt   
3        5      M  85.80  Central  73.60  Central  Commerce  73.30  Comm&Mgmt   
4        8      M  82.00  Central  64.00  Central   Science  66.00   Sci&Tech   
..     ...    ...    ...      ...    ...      ...       ...    ...        ...   
210    199      F  67.00  Central  70.00  Central  Commerce  65.00     Others   
211    202      M  54.20  Central  63.00   Others   Science  58.00  Comm&Mgmt   
212    207      M  41.00  Central  42.00  Central   Science  60.00  Comm&Mgmt   
213    209      F  43.00  Central  60.00   Others   Science  65.00  Comm&Mgmt   
214    215      M  62.00  Central  58.00   Others   Science  53.00  Comm&Mgmt   

    workex  etest_p specialisation  Masters      status  
0       No    55.00         Mkt&HR    58.80      Placed  
1      Yes    86.50        Mkt&Fin    66.28      Placed  
2       No    75.00        Mkt&Fin    57.80      Placed  
3       No    96.80        Mkt&Fin    55.50      Placed  
4      Yes    67.00        Mkt&Fin    62.14      Placed  
..     ...      ...            ...      ...         ...  
210     No    88.00         Mkt&HR    71.96  Not Placed  
211     No    79.00         Mkt&HR    58.44  Not Placed  
212     No    97.00        Mkt&Fin    53.39  Not Placed  
213     No    92.66         Mkt&HR    62.92  Not Placed  
214     No    89.00         Mkt&HR    60.22  Not Placed  

[215 rows x 14 columns]

In [4]:
dataset = dataset.drop(['sl_no', 'ssc_b', 'hsc_b'], axis = 1)
dataset

gender  ssc_p  hsc_p     hsc_s   CGPA   degree_t workex  etest_p  \
0        M  67.00  91.00  Commerce  58.00   Sci&Tech     No    55.00   
1        M  79.33  78.33   Science  77.48   Sci&Tech    Yes    86.50   
2        M  65.00  68.00      Arts  64.00  Comm&Mgmt     No    75.00   
3        M  85.80  73.60  Commerce  73.30  Comm&Mgmt     No    96.80   
4        M  82.00  64.00   Science  66.00   Sci&Tech    Yes    67.00   
..     ...    ...    ...       ...    ...        ...    ...      ...   
210      F  67.00  70.00  Commerce  65.00     Others     No    88.00   
211      M  54.20  63.00   Science  58.00  Comm&Mgmt     No    79.00   
212      M  41.00  42.00   Science  60.00  Comm&Mgmt     No    97.00   
213      F  43.00  60.00   Science  65.00  Comm&Mgmt     No    92.66   
214      M  62.00  58.00   Science  53.00  Comm&Mgmt     No    89.00   

    specialisation  Masters      status  
0           Mkt&HR    58.80      Placed  
1          Mkt&Fin    66.28      Placed  
2          Mkt&Fin    57.80      Placed  
3          Mkt&Fin    55.50      Placed  
4          Mkt&Fin    62.14      Placed  
..             ...      ...         ...  
210         Mkt&HR    71.96  Not Placed  
211         Mkt&HR    58.44  Not Placed  
212        Mkt&Fin    53.39  Not Placed  
213         Mkt&HR    62.92  Not Placed  
214         Mkt&HR    60.22  Not Placed  

[215 rows x 11 columns]

In [5]:
dataset["gender"] = dataset["gender"].astype('category')
dataset["hsc_s"] = dataset["hsc_s"].astype('category')
dataset["degree_t"] = dataset["degree_t"].astype('category')
dataset["workex"] = dataset["workex"].astype('category')
dataset["specialisation"] = dataset["specialisation"].astype('category')
dataset["status"] = dataset["status"].astype('category')

In [6]:
dataset.dtypes

gender            category
ssc_p              float64
hsc_p              float64
hsc_s             category
CGPA               float64
degree_t          category
workex            category
etest_p            float64
specialisation    category
Masters            float64
status            category
dtype: object

In [7]:
dataset["gender"] = dataset["gender"].cat.codes
dataset["hsc_s"] = dataset["hsc_s"].cat.codes
dataset["degree_t"] = dataset["degree_t"].cat.codes
dataset["workex"] = dataset["workex"].cat.codes
dataset["specialisation"] = dataset["specialisation"].cat.codes
dataset["status"] = dataset["status"].cat.codes

In [8]:
dataset

gender  ssc_p  hsc_p  hsc_s   CGPA  degree_t  workex  etest_p  \
0         1  67.00  91.00      1  58.00         2       0    55.00   
1         1  79.33  78.33      2  77.48         2       1    86.50   
2         1  65.00  68.00      0  64.00         0       0    75.00   
3         1  85.80  73.60      1  73.30         0       0    96.80   
4         1  82.00  64.00      2  66.00         2       1    67.00   
..      ...    ...    ...    ...    ...       ...     ...      ...   
210       0  67.00  70.00      1  65.00         1       0    88.00   
211       1  54.20  63.00      2  58.00         0       0    79.00   
212       1  41.00  42.00      2  60.00         0       0    97.00   
213       0  43.00  60.00      2  65.00         0       0    92.66   
214       1  62.00  58.00      2  53.00         0       0    89.00   

     specialisation  Masters  status  
0                 1    58.80       1  
1                 0    66.28       1  
2                 0    57.80       1  
3                 0    55.50       1  
4                 0    62.14       1  
..              ...      ...     ...  
210               1    71.96       0  
211               1    58.44       0  
212               0    53.39       0  
213               1    62.92       0  
214               1    60.22       0  

[215 rows x 11 columns]

In [9]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
X

array([[ 1.  , 67.  , 91.  , ..., 55.  ,  1.  , 58.8 ],
       [ 1.  , 79.33, 78.33, ..., 86.5 ,  0.  , 66.28],
       [ 1.  , 65.  , 68.  , ..., 75.  ,  0.  , 57.8 ],
       ...,
       [ 1.  , 41.  , 42.  , ..., 97.  ,  0.  , 53.39],
       [ 0.  , 43.  , 60.  , ..., 92.66,  1.  , 62.92],
       [ 1.  , 62.  , 58.  , ..., 89.  ,  1.  , 60.22]])

In [10]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5)

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000).fit(X_train, Y_train)
print(model.score(X_test, Y_test))
dataset.head()

0.8611111111111112


gender  ssc_p  hsc_p  hsc_s   CGPA  degree_t  workex  etest_p  \
0       1  67.00  91.00      1  58.00         2       0     55.0   
1       1  79.33  78.33      2  77.48         2       1     86.5   
2       1  65.00  68.00      0  64.00         0       0     75.0   
3       1  85.80  73.60      1  73.30         0       0     96.8   
4       1  82.00  64.00      2  66.00         2       1     67.0   

   specialisation  Masters  status  
0               1    58.80       1  
1               0    66.28       1  
2               0    57.80       1  
3               0    55.50       1  
4               0    62.14       1

In [13]:
model.predict([[0, 80, 75, 0, 80, 1, 1,88, 1, 77]])

array([1], dtype=int8)

In [14]:
X_test

array([[ 1.  , 54.  , 47.  , ..., 89.69,  1.  , 57.1 ],
       [ 1.  , 76.5 , 97.7 , ..., 97.4 ,  0.  , 74.01],
       [ 1.  , 67.  , 67.  , ..., 59.  ,  0.  , 69.72],
       ...,
       [ 1.  , 85.  , 60.  , ..., 60.  ,  0.  , 61.29],
       [ 1.  , 84.  , 90.9 , ..., 86.04,  0.  , 59.42],
       [ 0.  , 64.  , 70.2 , ..., 50.  ,  0.  , 62.5 ]])

In [15]:
model.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
      dtype=int8)

In [16]:
model.predict([[1, 60, 50, 0, 65, 0, 0,55, 0, 60]])

array([0], dtype=int8)

In [17]:
import pickle as pk
file = pk.dump(model, open('model.pkl', 'wb'))

In [18]:
# model_open = open("model.pickle","rb")
import pickle as pk
file_open = pk.load(open('model.pkl', 'rb'))
file_open.predict([[0,50, 40, 0, 50, 1, 0, 30, 1, 30]])
file_open.predict([[1, 60, 50, 0, 65, 0, 0,55, 0, 60]])

array([0], dtype=int8)

In [19]:
print(file_open)

LogisticRegression(max_iter=1000)


In [20]:
file_open.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
      dtype=int8)

In [21]:
import pickle as pk
file_open = pk.load(open('model.pkl', 'rb'))
Y_pred = file_open.predict(X_test)
Y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
      dtype=int8)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
 
# display confusion matrix
print(confusion_matrix(Y_test, Y_pred))
 
# display accuracy
print(accuracy_score(Y_test, Y_pred))

[[24  8]
 [ 7 69]]
0.8611111111111112
